version: '3.8'
name: dc-test-mysql
services:
  mysqldb:
    container_name: mysqldb-1
    #image: mysql:5.7
    build:
      context: .
      dockerfile: ./mysql.Dockerfile
    #restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      #- ./logs:/var/lib/mysql
      - ./mysql/:/etc/mysql/mysql.conf.d/ # Mount conf file

volumes: 
  db: